print('''Press Any Key To Continue :) :) :)''') 
a = input()
import os
os.system('pip install pyttsx3')
os.system('cls')
os.system('pip install opencv')
os.system('cls')
os.system('pip install pyautogui')
os.system('cls')
os.system('pip install keyboard')
os.system('cls')
os.system('pip install django')
os.system('cls')
os.system('pip install flask')
os.system('cls')
os.system('pip install pillow')
os.system('cls')

print('''Done :) :) :) :) :) :)''')
print('Press Any Key')
b = input()
